# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            No Name
tagline:          
url:              http://www.tjmapes.rocks
paginate:         1
baseurl:          /
author:
  name:           TJ Mapes
  url:            https://twitter.com/tjmapes
  email:          tj@riptapparel.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tjmapes

# Top Nav
pages_list:       
  About: '/about'
  Archive: '/archive'
