# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Digging My Own Grave
tagline:          
url:              http://diggingmyowngrave.com
paginate:         1
baseurl:          /
author:
  name:           TJ Mapes
  url:            https://twitter.com/tjmapes
  email:          tj@riptapparel.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tjmapes
